apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org{{ORG_NUMBER}}-ca-tls-cert
spec:
  isCA: false
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - localhost
    - org{{ORG_NUMBER}}-ca
    - org{{ORG_NUMBER}}-ca.test-network.svc.cluster.local
  ipAddresses:
    - 127.0.0.1
  secretName: org{{ORG_NUMBER}}-ca-tls-cert
  issuerRef:
    name: org{{ORG_NUMBER}}-tls-cert-issuer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: org{{ORG_NUMBER}}-ca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: org{{ORG_NUMBER}}-ca
  template:
    metadata:
      labels:
        app: org{{ORG_NUMBER}}-ca
    spec:
      containers:
        - name: main
          image: {{FABRIC_CONTAINER_REGISTRY}}/fabric-ca:{{FABRIC_CA_VERSION}}
          imagePullPolicy: IfNotPresent
          env:
            - name: FABRIC_CA_SERVER_CA_NAME
              value: "org{{ORG_NUMBER}}-ca"
            - name: FABRIC_CA_SERVER_DEBUG
              value: "false"
            - name: FABRIC_CA_SERVER_HOME
              value: "/var/hyperledger/fabric-ca-server"
            - name: FABRIC_CA_SERVER_TLS_CERTFILE
              value: "/var/hyperledger/fabric/config/tls/tls.crt"
            - name: FABRIC_CA_SERVER_TLS_KEYFILE
              value: "/var/hyperledger/fabric/config/tls/tls.key"
            - name: FABRIC_CA_CLIENT_HOME
              value: "/var/hyperledger/fabric-ca-client"
          ports:
            - containerPort: 443
          volumeMounts:
            - name: fabric-volume
              mountPath: /var/hyperledger
            - name: fabric-config
              mountPath: /var/hyperledger/fabric-ca-server/fabric-ca-server-config.yaml
              subPath: fabric-ca-server-config.yaml
            - name: tls-cert-volume
              mountPath: /var/hyperledger/fabric/config/tls
              readOnly: true
          readinessProbe:
            tcpSocket:
              port: 443
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: fabric-volume
          persistentVolumeClaim:
            claimName: fabric-org{{ORG_NUMBER}}
        - name: fabric-config
          configMap:
            name: org{{ORG_NUMBER}}-config
        - name: tls-cert-volume
          secret:
            secretName: org{{ORG_NUMBER}}-ca-tls-cert

---
apiVersion: v1
kind: Service
metadata:
  name: org{{ORG_NUMBER}}-ca
spec:
  ports:
    - name: tls
      port: 443
      protocol: TCP
  selector:
    app: org{{ORG_NUMBER}}-ca
