apiVersion: v1
kind: PersistentVolume
metadata:
  name: fabric-org{{ORG_NUMBER}}
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/hyperledger/org{{ORG_NUMBER}}.example.com
