apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: org{{ORG_NUMBER}}-tls-cert-issuer
spec:
  isCA: true
  privateKey:
    algorithm: ECDSA
    size: 256
  commonName: org{{ORG_NUMBER}}.example.com
  secretName: org{{ORG_NUMBER}}-tls-cert-issuer-secret
  issuerRef:
    name: root-tls-cert-issuer
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: org{{ORG_NUMBER}}-tls-cert-issuer
spec:
  ca:
    secretName: org{{ORG_NUMBER}}-tls-cert-issuer-secret
